
export { default as Logo } from "./logo.png";
export { default as Time } from "./time.png";
export { default as Visa } from "./visa.png";
export { default as Cubs1 } from "./Cubs1.png";
export { default as Cubs2 } from "./Cubs2.png";
export { default as Cubs3 } from "./Cubs3.png";
export { default as Cubs4 } from "./Cubs4.png";
export { default as Filipp } from "./filipp.png";
export { default as Master } from "./master.png";
export { default as Stick1 } from "./Stick1.png";
export { default as Stick2 } from "./Stick2.png";
export { default as Stick3 } from "./Stick3.png";
export { default as Stick4 } from "./Stick4.png";
export { default as Viber } from "./icon_viber.png";
export { default as Whatsapp } from "./icon_whatsapp.png"
export { default as Telegram } from "./icon_telegram.png";
export { default as Instagram } from "./icon_instagram.png";
export { default as LogoHorizontal } from "./logo-horizontal.png";
